title: The first step for GitHub pages
author: LJW
email: wwwnsdnjs@naver.com
description: > # this means to ignore newlines until "baseurl:"
  It is the first step that advance to the GitHub professor.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: junwon25 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
